name: "NPM Outdated Check"
description: "Runs npm outdated, node-check-updates, and update --dry-run, and adds a customizable comment to the Pull Request with output."
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  columns:
    description: "Customize Table Columns"
    default: "n,c,w,l"
  latest:
    description: "Report if Latest > Wanted"
    default: "true"
  heading:
    description: "Comment Heading"
    default: "### NPM Outdated Check"
  open:
    description: "Details Open by Default"
    default: "true"
  ncu:
    description: "Show npm-check-updates Output"
    default: "true"
  update:
    description: "Show npm update --dry-run Output"
    default: "true"
  link:
    description: "Use Link for Names"
    default: "true"
  exclude:
    description: "CSV of Package Names to Exclude"
  fail:
    description: "Fail Job if Updates are Found"
    default: "false"
  summary:
    description: "Add Summary to Job"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  outdated:
    description: "Outdated JSON Object"
  ncu:
    description: "NPM Check Updates Output"
  update:
    description: "NPM Update Dry Run Output"
  markdown:
    description: "Results Markdown Table"

runs:
  using: "node20"
  main: "dist/index.js"
