name: "NPM Outdated Check"
description: "Runs npm outdated and comments on a Pull Request with a customizable table of packages current, wanted, and latest versions."
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  columns:
    description: "Column Order and Visibility"
    required: false
    default: "n,c,w,l"
  latest:
    description: "Report if Latest > Wanted"
    required: false
    default: "true"
  heading:
    description: "Update Heading Text"
    required: false
    default: "### NPM Outdated Check"
  open:
    description: "Details Open by Default"
    required: false
    default: "true"
  ncu:
    description: "Show npm-check-updates Output"
    required: false
    default: "true"
  update:
    description: "Show npm update --dry-run Output"
    required: false
    default: "true"
  link:
    description: "Use Link for Names"
    required: false
    default: "true"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"
  token:
    description: "GitHub Token"
    required: false
    default: ${{ github.token }}

outputs:
  json:
    description: "Changes JSON Object"
  markdown:
    description: "Changes Markdown Table"

runs:
  using: "node20"
  main: "dist/index.js"
